export const ErrorCode = {
  // Global
  RATE_LIMIT: 'RATE_LIMIT',
  UNAUTHORIZED: 'UNAUTHORIZED',

  // Auth
  AUTH_VALIDATION: 'AUTH_VALIDATION',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_SERVER_ERROR: 'AUTH_SERVER_ERROR',

  // Contact
  CONTACT_VALIDATION: 'CONTACT_VALIDATION',
  CONTACT_MAILER: 'CONTACT_MAILER',

  // Account
  ACCOUNT_VALIDATION: 'ACCOUNT_VALIDATION',
  ACCOUNT_UNAUTHORIZED: 'ACCOUNT_UNAUTHORIZED',

  // Billing
  BILLING_REQUEST_FAILED: 'BILLING_REQUEST_FAILED',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]
